version: '3.8'

services:
  mohandesi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORKING_DIR: /app
    container_name: mohandesi
    hostname: django
    restart: 'always'

    command: gunicorn -c config/gunicorn/conf.py --chdir kernel kernel.wsgi.application
    # command: python manage.py runserver 0.0.0.0:8600

    volumes:
      # Source Code of project
      - .:/app
      # Collect Static files
      - static_volume:/app/media/collectstatic
      # Media Files (Uploads)
      - media_volume:/app/media/upload

    stop_grace_period: 1m30s

    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:32226"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - 32226:32226
    networks:
      - database_network
      - cache_network