version: '3.8'

services:
  mohandesi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORKING_DIR: /app
    restart: always
    container_name: mohandesi-ecom
    command: gunicorn -c configs/gunicorn/conf.py --chdir project project.wsgi:application
    volumes:
      - .:/app
      # Collectstatic files for Nginx
      - /home/devops/backups/mohandesi/collectstatic:/app/media/collectstatic
      # Media Files (Upload) for Nginx
      - /home/devops/backups/mohandesi/upload:/app/media/upload
      # Django Logging
      - /var/log/mohandesi:/app/log
    stop_grace_period: 1m30s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:32226"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "32226:32226"
    networks:
      - database_network
      - cache_network
      - webserver_network
networks:
  database_network:
    external: true
  cache_network:
    external: true
  webserver_network:
    external: true